config/routes.rb
Alice::Application.routes.draw do

  # namespace :pluto do resources :process_instances end

  root to: 'root#index'

  devise_for :users
  resources :users

  namespace :core do
    resources :machines
    resources :applications do
      delete 'cache', on: :member, action: 'bust_cache'
    end
    resources :releases
  end

  namespace :http do
    resources :backends
    resources :passers
    resources :routers
  end

  scope path: '/core/applications/:application_id', as: 'core_application' do
    namespace :http do
      resources :domain_rules
      resources :path_rules
    end

    namespace :pluto do
      resources :environment_variables
      resources :process_definitions
    end
  end

  namespace :api_v1 do
    post 'register',              to: 'endpoints#register'
    post 'probe_report',          to: 'endpoints#probe_report'
    get  'endpoints',             to: 'endpoints#index'
    get  'routers',               to: 'endpoints#routers'
    put  'register_static_paths', to: 'applications#register_static_paths'

    post 'releases',
      to: 'releases#create'

    delete 'releases/:id',
      to: 'releases#destroy'

    post 'releases/:id/activate',
      to: 'releases#activate'

    post 'applications/:application_name/maintenance',
      to: 'applications#maintenance_mode_on',
      constraints: { application_name: /.*/ }

    delete 'applications/:application_name/maintenance',
      to: 'applications#maintenance_mode_off',
      constraints: { application_name: /.*/ }

    delete 'applications/:application_name/cache',
      to: 'applications#bust_cache',
      constraints: { application_name: /.*/ }

    get 'machines/:machine_host/routers',
      to: 'machines#routers',
      constraints: { machine_host: /.*/ }

    get 'machines/:machine_host/endpoints',
      to: 'machines#endpoints',
      constraints: { machine_host: /.*/ }

    get 'machines/:machine_host/tasks',
      to: 'machines#tasks',
      constraints: { machine_host: /.*/ }

    post 'machines/:machine_host/probe_report',
      to: 'machines#probe_report',
      constraints: { machine_host: /.*/ }

  end

  # mount FnordMetric.embedded, at: '/stats'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.scoped

    respond_to do |format|
      format.html { @users = @users.page(params[:page]) }
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html do
          flash[:success] = 'User was successfully created.'
          redirect_to @user
        end
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html do
          flash[:success] = 'User was successfully updated.'
          redirect_to @user
        end
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/views/users/_form.html.erb
<%= semantic_form_for @user do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
    <%= f.input :email, :hint => "The user's email" %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button :button_html => {:class => "primary"} %>
  <% end %>
<% end %>

app/views/users/_list.html.erb
<div class="span10">
  <table class="zebra-striped">
    <thead>
      <tr>
        <th>Email</th>
      </tr>
    </thead>

    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= link_to user.email, user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="span4">
  <%= link_to 'New User', new_user_path, class: 'btn large success' %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @uset %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<div class="page-header row">
  <h1>Users</h1>
</div>
<div class="row fit-height">
  <%= render 'list', users: @users %>
  <div class="span10"><%= paginate @users %></div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= flash_messages %>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>